### ISSUE TITLE
Is it possible to return the airport code

### ISSUE THREAD

**Issue by caique0202** [MatejMecka/GoogleFlightScraper#2]
Have the airport code would be a really good improvement:

Ex: 
Salt Lake City - SLC
Washington, D.C. - DCA

Thanks
Carlos

**Comment by MatejMecka** [comment]
Hi There!

Yes, that's possible I'll implement it right now!

Thanks for your suggestion

**Comment by MatejMecka** [comment]
The [latest commit](https://github.com/MatejMecka/GoogleFlightScraper/commit/a229ae2a42e878df7df315b406375e49dfe74083) has the suggestion implemented. To access them use  `DepartureCode` and `ArrivalCode`.
